apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .PodLabelValue }}
  name: {{ .GrafanaDeploymentName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .PodLabelValue }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .PodLabelValue }}
      name: grafana
    spec:
      initContainers:
        - env:
            - name: GRAFANA_PLUGINS
              value: ""
          image: '{{ .PluginsInitContainerImage }}:{{ .PluginsInitContainerTag }}'
          imagePullPolicy: IfNotPresent
          name: grafana-plugins-init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/plugins
              name: grafana-plugins
      containers:
        - image: '{{ .GrafanaImage }}:{{ .GrafanaVersion }}'
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana-http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/dashboards
              name: {{ .GrafanaProvidersConfigMapName }}
            - mountPath: /etc/grafana/provisioning/datasources
              name: {{ .GrafanaDatasourcesConfigMapName }}
            - mountPath: /etc/grafana/provisioning/notifiers
              name: grafana-notifiers-provisioning
            - mountPath: /etc/grafana-dashboards
              name: {{ .GrafanaDashboardsConfigMapName }}
            - mountPath: /var/lib/grafana
              name: grafana-data
            - mountPath: /var/log/grafana
              name: grafana-logs
            - mountPath: /etc/grafana/
              name: {{ .GrafanaConfigMapName }}
            - mountPath: /var/lib/grafana/plugins
              name: grafana-plugins
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .GrafanaServiceAccountName}}
      serviceAccountName: {{ .GrafanaServiceAccountName }}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: {{ .GrafanaProvidersConfigMapName}}
          name: {{ .GrafanaProvidersConfigMapName }}
        - configMap:
            name: {{ .GrafanaDatasourcesConfigMapName }}
          name: {{ .GrafanaDatasourcesConfigMapName }}
        - configMap:
            name: {{ .GrafanaDashboardsConfigMapName }}
          name: {{ .GrafanaDashboardsConfigMapName }}
        - configMap:
            name: {{ .GrafanaConfigMapName }}
          name: {{ .GrafanaConfigMapName }}
        - emptyDir: {}
          name: grafana-data
        - emptyDir: {}
          name: grafana-logs
        - emptyDir: {}
          name: grafana-plugins
        - emptyDir: {}
          name: grafana-notifiers-provisioning
